### ISSUE TITLE
Requirements.txt needs to be reformatted

### ISSUE THREAD

**Issue by ggroenendale** [blackkerouac/Data_Visualization-Project_2#7]
Looks like the requirements.txt file is copied from the head of the flask app python file. Your requirements.txt file should list just the necessary libraries. "from" or "import" shouldn't be in this list. If you have to install it with pip then it should be listed in the file. Try to add versions for the libraries, just use the current version.

**Comment by Bonnie-jo** [comment]
Created new Virtual Environment, installed all requirements, completed "pip freeze" and selected all items listed, entered that information into the requirements.txt file and re-committed.
